# Generated by Django 3.0.7 on 2020-07-01 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_t', models.CharField(max_length=200)),
                ('p_d', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'db_table': 'a01_question',
            },
        ),
        migrations.CreateModel(
            name='c',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_t', models.CharField(max_length=200)),
                ('v', models.IntegerField(default=0)),
                ('q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a01.q')),
            ],
            options={
                'db_table': 'a01_choice',
            },
        ),
    ]
