# Generated by Django 3.0.7 on 2020-12-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2ji_bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='bbs',
            name='update_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
