# Generated by Django 3.0.7 on 2020-12-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w2ji_bbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbs',
            old_name='auther',
            new_name='author',
        ),
    ]
