# Generated by Django 3.0.7 on 2020-06-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='아이디를 입력하세요', max_length=20, verbose_name='아이디')),
                ('email', models.CharField(help_text='이메일 주소를 입력하세요', max_length=100, verbose_name='이메일')),
                ('user_ps', models.CharField(help_text='비밀번호를 입력하세요', max_length=50, verbose_name='비밀번호')),
                ('user_nm', models.CharField(help_text='이름를 입력하세요', max_length=50, verbose_name='이름')),
                ('user_hp', models.CharField(help_text='휴대 전화번호를 입력하세요', max_length=50, verbose_name='휴대폰')),
                ('user_tel', models.CharField(help_text='연락처를 입력하세요', max_length=50, verbose_name='연락처')),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
