# Generated by Django 3.0.7 on 2020-08-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('update_dt', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'db_table': 'test_question',
            },
        ),
        migrations.CreateModel(
            name='test_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'test_choice',
            },
        ),
    ]
