# Generated by Django 3.0.7 on 2020-08-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_song', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='test_1',
        ),
        migrations.DeleteModel(
            name='test_2',
        ),
    ]
