# Generated by Django 3.1 on 2020-08-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_song', '0002_auto_20200825_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='image/')),
            ],
            options={
                'db_table': 'test_post',
            },
        ),
    ]
