# Generated by Django 3.0.7 on 2021-01-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_nm', models.CharField(max_length=126, null=True, verbose_name='그룹명')),
                ('menu_nm', models.CharField(max_length=126, verbose_name='메뉴명')),
                ('menu_url', models.CharField(max_length=256, verbose_name='메뉴 링크')),
                ('menu_descript', models.TextField(null=True, verbose_name='메뉴 설명')),
                ('group_sort', models.IntegerField(verbose_name='그룹순서')),
                ('menu_sort', models.IntegerField(verbose_name='메뉴순서')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'w2ji_menu',
            },
        ),
    ]
