# Generated by Django 3.0.7 on 2021-01-12 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('w2ji_menu', '0002_menu_use_yn'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_nm', models.CharField(max_length=126, verbose_name='그룹명')),
                ('group_sort', models.IntegerField(verbose_name='그룹순서')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'w2ji_menu_group',
            },
        ),
        migrations.RemoveField(
            model_name='menu',
            name='group_sort',
        ),
        migrations.AlterField(
            model_name='menu',
            name='group_nm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w2ji_menu.group'),
        ),
    ]
