# Generated by Django 3.0.7 on 2021-01-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2ji_menu', '0005_auto_20210114_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_icon',
            field=models.CharField(max_length=126, null=True, verbose_name='아이콘'),
        ),
    ]
