# Generated by Django 3.1 on 2021-01-04 07:02

from django.db import migrations
import w2ji_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('w2ji_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', w2ji_user.models.UserManager()),
            ],
        ),
    ]
