# Generated by Django 3.0.7 on 2020-08-13 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('company_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='회사코드')),
                ('company_nm', models.CharField(max_length=40, verbose_name='회사명')),
                ('use_yn', models.CharField(default='y', max_length=1, verbose_name='사용유무')),
                ('update_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'zsy_company_info',
                'unique_together': {('company_id',)},
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='아이디를 입력하세요', max_length=20, verbose_name='아이디')),
                ('user_ps', models.CharField(help_text='비밀번호를 입력하세요', max_length=50, verbose_name='비밀번호')),
                ('user_nm', models.CharField(max_length=50, verbose_name='이름')),
                ('email', models.CharField(blank=True, help_text='이메일 주소를 입력하세요', max_length=100, verbose_name='이메일')),
                ('user_hp', models.CharField(blank=True, help_text='휴대 전화번호를 입력하세요', max_length=50, verbose_name='휴대폰')),
                ('user_tel', models.CharField(blank=True, help_text='연락처를 입력하세요', max_length=50, verbose_name='연락처')),
                ('use_yn', models.CharField(default='y', max_length=1, verbose_name='사용유무')),
                ('access_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('update_id', models.CharField(blank=True, max_length=20, verbose_name='수정 아이디')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zsy.CompanyInfo')),
            ],
            options={
                'db_table': 'zsy_user_info',
                'unique_together': {('company_id', 'user_id')},
            },
        ),
    ]
