# Generated by Django 3.1 on 2020-08-28 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zsy', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinfo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='company_id',
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
