# Generated by Django 3.0.7 on 2021-01-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.CharField(max_length=126, verbose_name='일자')),
                ('sale', models.IntegerField(verbose_name='판매금액')),
                ('amount', models.IntegerField(verbose_name='수량')),
                ('cost', models.IntegerField(verbose_name='단가')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
            options={
                'db_table': 'w2ji_chart',
            },
        ),
    ]
