# Generated by Django 3.0.7 on 2021-01-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w2ji_tinydash', '0002_auto_20210128_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='create_dt',
        ),
    ]
