# Generated by Django 3.0.7 on 2021-01-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2ji_tinydash', '0003_remove_chart_create_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='mon',
            field=models.CharField(max_length=126, null=True, verbose_name='년월'),
        ),
    ]
