# Generated by Django 3.0.7 on 2021-01-29 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w2ji_tinydash', '0004_chart_mon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chart',
        ),
    ]
