# Generated by Django 3.0.7 on 2021-01-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('w2ji_tinydash', '0005_delete_chart'),
    ]

    operations = [
        migrations.CreateModel(
            name='chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.CharField(max_length=126, verbose_name='일자')),
                ('mon', models.CharField(max_length=126, null=True, verbose_name='년월')),
                ('sale', models.IntegerField(verbose_name='판매금액')),
                ('amount', models.IntegerField(verbose_name='수량')),
                ('cost', models.IntegerField(verbose_name='단가')),
            ],
            options={
                'db_table': 'w2ji_chart',
            },
        ),
    ]
